#!/bin/sh
# Action script to collect battery status when the power connector is
# inserted or removed.
#
# Copyright: Copyright (c) 2013 Petter Reinholdtsen
# License:   GPL-2+
#

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case "${1}" in
    false|true)
	if [ -x /usr/share/battery-stats/collect-csv ]; then
	    /usr/share/battery-stats/collect-csv
	fi
        ;;
esac
