#!/bin/sh
#
# This file is part of the battery-stats package.
# Copyright (C) 2002 Karl E. Jørgensen <karl@jorgensen.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software

set -e

if [ $# -eq 0 ]
then
    files=`ls -1 /var/log/battery-stats /var/log/battery-stats.* 2>/dev/null` \
      || true
else
    files="$@"
fi

for file in $files
do
    case "$file" in
	*.gz)
	    zcat $file
	    ;;
	*)
	    cat $file
    esac
done

